drop table sc_bankaccount;
drop table sc_account;

CREATE TABLE sc_account (
    username varchar(255),
    clientId varchar(255) NOT NULL PRIMARY KEY,
    funds decimal(30,2) NOT NULL
);

CREATE TABLE sc_bankaccount (
    clientId varchar(255),
    account_number varchar(255) NOT NULL,
    bank_name varchar(255) NOT NULL,
    balance decimal(30,2),
    PRIMARY KEY(account_number),
    FOREIGN KEY(clientId) REFERENCES sc_account(clientId)
); 


--------------------------------------------------------
--  File created - Wednesday-October-12-2022   
--------------------------------------------------------
DROP TABLE "SC_TRADE";
DROP TABLE "SC_HOLDING";
--------------------------------------------------------
--  DDL for Table SC_TRADE
--------------------------------------------------------

  CREATE TABLE "SC_TRADE" 
   (	"TRADE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CLIENTID" VARCHAR2(255 BYTE), 
	"TRADE_TYPE" CHAR(1 BYTE), 
	"S_ID" NUMBER(6,0), 
	"QUANTITY" NUMBER(10,2), 
	"PRICE" NUMBER(10,2),
	"TRADE_TIME" TIMESTAMP(0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table SC_HOLDING
--------------------------------------------------------

  CREATE TABLE "SC_HOLDING" 
   (	"HOLDING_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"S_ID" NUMBER, 
	"QTY" NUMBER(10,2), 
	"INVESTED_AMOUNT" NUMBER(10,2), 
	"CLIENTID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
----- REM INSERTING into  SC_TRADE
----- SET DEFINE OFF;
----- REM INSERTING into SC_HOLDING
----- SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SC_TRADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SC_TRADE_PK" ON "SC_TRADE" ("TRADE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SC_HOLDING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SC_HOLDING_PK" ON "SC_HOLDING" ("HOLDING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table SC_TRADE
--------------------------------------------------------

---  ALTER TABLE "SC_TRADE" MODIFY ("TRADE_ID" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" MODIFY ("TRADE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" MODIFY ("S_ID" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" MODIFY ("TRADE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SC_TRADE" ADD CONSTRAINT "SC_TRADE_PK" PRIMARY KEY ("TRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SC_HOLDING
--------------------------------------------------------

--  ALTER TABLE "SC_HOLDING" MODIFY ("HOLDING_ID" NOT NULL ENABLE);
  ALTER TABLE "SC_HOLDING" MODIFY ("S_ID" NOT NULL ENABLE);
  ALTER TABLE "SC_HOLDING" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "SC_HOLDING" MODIFY ("INVESTED_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SC_HOLDING" ADD CONSTRAINT "SC_HOLDING_PK" PRIMARY KEY ("HOLDING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSAUX"  ENABLE;
  
  
  
DROP TABLE "SC_SECURITIES";

CREATE TABLE sc_securities (
    s_id NUMBER(6,0) PRIMARY KEY,
    s_name  VARCHAR2(200) NOT NULL,
    s_code VARCHAR2(200) NOT NULL UNIQUE,
    s_ltp DECIMAL(10,2) NOT NULL,
    s_asset_class VARCHAR2(200)
);



DROP TABLE "SC_PREFERENCES";
DROP TABLE "SC_USERS";

CREATE TABLE sc_users (
    first_name varchar(255),
    last_name varchar(255),
    date_of_birth DATE,
    email varchar(255),
    phone_number varchar(255),
    username varchar(255),
    user_password varchar(255),
    primary key(username)
);

CREATE TABLE sc_preferences (
    username varchar(255),
    purpose varchar(255),
    risk_tolerance INT,
    income_category varchar(255),
    length_of_investment varchar(255),
    FOREIGN KEY (username) REFERENCES sc_users(username)
);